### ISSUE TITLE
YOLOv7 GPU

### ISSUE THREAD

**Issue by FabioColombo1967** [hshatti/TONNXRuntime#10]
I'm trying YOLO V7 sample but inference return failed code 108
PC with 4060 GPU

Someone may help me?

Thanks in advance

![immagine](https://github.com/user-attachments/assets/068f429d-45a8-4e6e-8b5a-ec5d1db9b5e8)

![immagine](https://github.com/user-attachments/assets/17ad0452-69dd-4181-9d62-47796c3fd661)

**Comment by hshatti** [comment]
Hi , happy to help!
It looks like you are using an outdated version (1.10 in your case) of onnxruntime.dll,  Please first try to download the DirectML onnxruntime release version [1.16.1](
https://github.com/microsoft/onnxruntime/releases/download/v1.16.2/Microsoft.ML.OnnxRuntime.DirectML.1.16.2.zip) , place the extracted dlls next to the exe file then try again, it may seem that releases beyond version 1.16 could encounter some incompatility issues with some older models or with this implementation, I will try yo release an updated version soon but let me know if this solution works

Cheers
H
