### ISSUE TITLE
error

### ISSUE THREAD

**Issue by firemen01** [hshatti/TONNXRuntime#7]
//  Input:=TOrtTensor<single>.Create([paddedHeight,paddedWidth,3 ]);
  Input:=TOrtTensor<single>.Create([paddedWidth,paddedHeight,3 ]);

**Comment by firemen01** [comment]
Haven't tried connecting models from https://github.com/Anjok07/ultimatevocalremovergui ?

**Comment by hshatti** [comment]
> // Input:=TOrtTensor.Create([paddedHeight,paddedWidth,3 ]); Input:=TOrtTensor.Create([paddedWidth,paddedHeight,3 ]);

Appreciate if you can add more context describing the issue so I can address it, for example : what is the definition of these identifiers in the parameter? what is the error message you are getting?, what is the compiler you are using and what are you trying to do? and I would be happy to help.

> Haven't tried connecting models from https://github.com/Anjok07/ultimatevocalremovergui ?

Not sure how this can be an issue? There are gazillions of models out there that I have not tried, but I would be curious to know how it works for other developers, I wouldn't hesitate to improve the library or add new features and give some tips, but I cannot make an example of every released model out there :).

**Comment by firemen01** [comment]
https://github.com/hshatti/TONNXRuntime/blob/main/examples/Delphi/FasterRCNN10/delphi_unit.pas
change Width and Height
if the image width is less than the height it says range error

 Input:=TOrtTensor<single>.Create([paddedHeight,paddedWidth,3 ]);
...
input[x,y,0]   { Input[paddedHeight, paddedWidth]} and you can do it input size (y,x)

**Comment by hshatti** [comment]
Just updated the example and added some fixes along with some improvements, please make a `git pull` to get the updates and try again and let me know, thanks for your observation, and appreciate if you star this repository, further examples from different models will be uploaded soon
Best
